### ISSUE TITLE
＜学生＞プロフィール項目の決定

### ISSUE THREAD

**Issue by shizunaito** [reno-shelter/ios_app#2]
学生側アプリの初回ログイン時、プロフィール入力画面で入力してもらう情報の項目を決定したいです。  
以下の項目を候補として考えたので、追加したほうがよいものや、必要のないものがあるか、ご意見いただきたいです。

- 生年月日
- 性別
- 電話番号
- 学校種別（大学、大学院）
- 学校名
- 文理区分
- 学年
- 卒業予定年度
- 志望業界（任意）
- 志望職種（任意）

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

### 追加項目
* 氏名
* ふりがな

### 不要項目
* 学年→学年は卒業年度に対して当てにならない情報なので、卒業年度の予定さえわかっていれば、不要になると考えます

### 微妙（議論が必要）
* 学部学科→正直、管理側としては欲しい情報であることは間違いない。ただし、書くのが面倒で、ここで離脱するのであれば、避けてもいいかなとは思う。ユーザー視点で見た時にどう？

**Comment by shizunaito** [comment]
@hirokiyamada-reno 

ご確認ありがとうございます。
不要項目については取り消します。

## 追加項目について

- 氏名　→　登録時にe-mailアドレスとパスワードと共に入力する予定でしたが、それを取り消してプロフィール情報入力時にフリガナと共に聞くのがよいでしょうか。

- 学部学科　→　自分が今まで登録した就活支援サービスのサイトでは毎回聞かれていることで、文章を作らなければいけない等の手間があるわけでもないので、特別面倒と感じることはないかと思います。

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

> 氏名　→　登録時にe-mailアドレスとパスワードと共に入力する予定でしたが、それを取り消してプロフィール情報入力時にフリガナと共に聞くのがよいでしょうか。

タイミングは不自然じゃなければどちらでもいいかな。
* 登録時に入力する際に、ふりがなも聞くでもいいし、
* 登録時は漢字のみ。プロフィールのときに漢字の名前は最初から埋まっていて、ふりがなのみ記入でもいいし
* 登録時の名前登録をやめて、プロフィール時に漢字、ふりがな入力でも。
一番作りやすいのでいいかなと思う。

> 学部学科　→　自分が今まで登録した就活支援サービスのサイトでは毎回聞かれていることで、文章を作らなければいけない等の手間があるわけでもないので、特別面倒と感じることはないかと思います。

手間に感じないようであれば、手入力での項目を追加してもらえるといいかな。あとは必須にするかどうかだね。まぁ、これはリリース後、そこで離脱が多いようであれば、必須を外すという意思決定でいいかなと思います。

**Comment by shizunaito** [comment]
@hirokiyamada-reno 

### 氏名について

作りやすさを考えると、登録時の名前登録をやめて、プロフィール時に漢字・ふりがな入力がよいかと思います。それで問題なければそう変更します。

### 学部学科について

手入力での項目追加で、初めは必須にします。

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

上記、両方ともこれでオッケーです！！
最後にこのissueで確定したことをまとめて、クローズしちゃってください！！

**Comment by shizunaito** [comment]
# 学生側登録情報

## 新規登録時

- emailアドレス
- パスワード

## 初回ログイン時

- 氏名
- ふりがな
- 生年月日
- 性別
- 電話番号
- 学校種別（大学、大学院）
- 学校名
- 文理区分
- 学部
- 学科
- 卒業予定年度
- 志望業界（任意）
- 志望職種（任意）
