### ISSUE TITLE
＜学生＞紹介認証方法決定

### ISSUE THREAD

**Issue by shizunaito** [reno-shelter/ios_app#3]
紹介機能について、どのユーザーが紹介したかを認識するためにどのような方法をとるかを決定したいです。
以下、認証方法の提案です。ご意見いただきたいです。宜しくお願いします。

## 紹介する側の設定

- 新規登録時、すべてのユーザーにランダムで紹介コードを割り当て、ユーザー情報としてデータベースに保管。
- 紹介コードはマイページのプロフィールに表示。  
また、LINE・Messenger等でURLを送信する際に、メッセージとして同時に送信。

## 紹介される側の設定

- 初回登録時に紹介コードを入力する欄を追加し、ユーザー情報としてデータベースに保管（自分の紹介IDとは別の場所）。
- 入力があった場合、紹介した側にRENO公式アカウントで通知。

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

実現したいこととしては

1. 誰が誰を紹介したかがわかる
1. 紹介が完了（アカウント登録か、初回の面談なのか、トリガーは要相談）したときに通知がくる
1. 紹介をカウントすることができる

この三点だね。

なので、それを実現するためには、

誰が誰を紹介したかがわかる→全ユーザーに別々の紹介URLを発行する
紹介が完了したときに通知がくる→トリガーが発動した時に、RENO公式アカウントで通知
紹介をカウントすることができる→データベースに、URLと紐づく紹介コードのカラムを作成し、紹介用のURLから登録があった場合には、登録ユーザーに紹介コードを登録する。

これらの要件があれば良さそうかな？

**Comment by shizunaito** [comment]
@hirokiyamada-reno 

## RENO側

- 初回面接もしくはチャット上のやり取りで紹介かどうかを聞き、
紹介の場合、利用者一覧から紹介した側を選択し、紹介された側の氏名を入力する。

## 学生側

- 紹介はURL等の送信のみ。
- 紹介された側は初回面談等で担当者に紹介者を伝える。
- RENO側が紹介者登録をすると、RENO公式アカウントで通知。  
また、紹介者一覧に自分が紹介した利用者の氏名が表示される。

上記内容で決定でよろしいでしょうか。
ご確認お願いします。

**Comment by shizunaito** [comment]
@hirokiyamada-reno 

すみません。RENO側修正です。

## 変更点（RENO）

紹介の場合、利用者一覧から __ 紹介された側の学生 __ を選択し、紹介者を選択ボタンをタップ。
利用者一覧が表示されるのでその中から __ 紹介した側 __ を選択する。

## 変更理由

氏名の入力では固有性がないため（同姓同名等の可能性がある）。
また、データベースに格納する際に、紹介された側と紐付ける方が簡略化できるため。

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

上記確認しました。オッケーです。

**Comment by shizunaito** [comment]
# 決定事項

## RENO側

- 初回面接もしくはチャット上のやり取りで紹介かどうかを聞き、 紹介の場合、利用者一覧から紹介された側の学生を選択し、紹介者を選択ボタンをタップ。
利用者一覧が表示されるのでその中から紹介した側を選択する。

## 学生側

- 紹介はURL等の送信のみ。
- 紹介された側は初回面談等で担当者に紹介者を伝える。
- RENO側が紹介者登録をすると、RENO公式アカウントで通知。  
また、紹介者一覧に自分が紹介した利用者の氏名が表示される。
