### ISSUE TITLE
＜RENO＞表示する学生プロフィール項目決定

### ISSUE THREAD

**Issue by shizunaito** [reno-shelter/ios_app#4]
利用者一覧から学生名をタップしたときと、担当未登録者一覧から学生名をタップしたとき、それぞれにプロフィール情報として何を表示するか決定したいです。
以下、提案ですのでご意見いただきたいです。

## 利用者一覧からの表示

- ふりがな
- 担当者
- 性別
- 学校種別（大学、大学院）
- 学校名
- 学部
- 学科
- 卒業予定年度
- 志望業界（任意）
- 志望職種（任意）

## 担当未登録者一覧からの表示

- ふりがな
- 性別
- 学校種別（大学、大学院）
- 学校名
- 文理区分
- 学部
- 学科
- 卒業予定年度
- 志望業界（任意）
- 志望職種（任意）

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

利用者一覧のほうに電話番号はあると助かる。
他は大丈夫だね。あとは、実際に文字とか入れてみて、どのくらいのサイズ感、ボリュームになるかを見て、ボリュームが多そうで見た目が厳しくなるようだったら、削る形でいいと思います。

**Comment by shizunaito** [comment]
@hirokiyamada-reno 

承知しました。
一旦下記項目で仮決定にして、画面出来次第調整します。

## 利用者一覧からの表示

- ふりがな
- 担当者
- 性別
- 電話番号
- 学校種別（大学、大学院）
- 学校名
- 学部
- 学科
- 卒業予定年度
- 志望業界（任意）
- 志望職種（任意）

## 担当未登録者一覧からの表示

- ふりがな
- 性別
- 学校種別（大学、大学院）
- 学校名
- 文理区分
- 学部
- 学科
- 卒業予定年度
- 志望業界（任意）
- 志望職種（任意）

**Comment by hirokiyamada-reno** [comment]
オッケーです！！

**Comment by kokihori** [comment]
てすと
