### ISSUE TITLE
ウェルカムページについて

### ISSUE THREAD

**Issue by kokihori** [reno-shelter/ios_app#5]
# What
ウェルカムページの項目デザインを詰める。

# Why
ユーザーが最初に通るページのため、見やすさ、わかりやすさ、美しさを追求するため。

# Goal
ウェルカムページのデザインと内容を決定。

**Comment by hirokiyamada-reno** [comment]
現状の選択肢としては

1. iettyみたいに登録前のページで用意する
2. 登録が完了した後の最初のページで用意する
3. 用意しない

この三つですかね？

**Comment by kokihori** [comment]
@hirokiyamada-reno @shizunaito 
もし自分がユーザーだったとしたら、登録前になんのためのアプリなのかを知りたいかな。結構詳細な情報を記入する必要があるので説明なしでは不安になる。
ということで１に一票。

**Comment by shizunaito** [comment]
@hirokiyamada-reno ＠kokihori
私も1が良いかと思います。
確かに登録前に説明があった方が情報入力の際に安心だと思うからです。
ただ、現段階での使用状況の想定として、既に相談を受けている学生の利用、もしくはその紹介での利用だけならば、必要性があるかは疑問ではあります。

**Comment by hirokiyamada-reno** [comment]
@kokihori  @shizunaito 

そうだね。基本的な方向性としては１が最有力。
論点としては、紹介する学生がどのような情報を渡して、紹介するかというところだね。

仮に、全てアプリの使い方とかも説明した上での紹介だったら、不要になるよね。
ただ、これはすごく丁寧な一部の学生だと思うな。

今までの経験だと、紹介の仕方で一番多いのは

「私が相談に乗ってもらって、すごく参考になった人がいるから、君も相談に乗って貰えば？」

これなので、これをアプリに転換すると

「私が相談に乗ってもらって、すごく参考になった人がいるから、君も相談に乗って貰えば？このアプリを使ったら、その人と無料で連絡とか面談してもらえるよ」

こんな感じの紹介になるかなと。そうなると、連絡、面談という単語しか出てこないので、全体像を把握するのはすごく難しいと思う。なので、事前に全体像（このアプリで何ができるのか）を伝えるのは有効だとは思うね。

**Comment by shizunaito** [comment]
説明画面は登録前ページで用意する　に決定します。
