### ISSUE TITLE
RENO社員アカウントの登録

### ISSUE THREAD

**Issue by shizunaito** [reno-shelter/ios_app#6]
# What
RENO社員アカウントの登録方法についての議論

# Why
RENO社員アカウントのセキュリティ強化のため。

# Goal
RENO社員としての登録の際のルールを決定

**Comment by shizunaito** [comment]
@hirokiyamada-reno 

RENO社員アカウントの登録ですが、学生側と同じような登録方法にすると、誰でも登録できてしまうため少々問題があるかと思われます。
登録の際にRENO社員のみ登録することができるようなルールを設けたいです。

考えた方法は以下のとおりです。

- RENOアカウントのパスワードは全て統一にし、そのパスワードを入力しないと登録できないようにする。
- メールアドレスをreno-worksのみ登録できるようにする。
- メールアドレス・パスワードとは別にコードを用意しておき、それを入力して登録するようにする。

どのようにするのがよいか、ご意見頂きたいです。
宜しくお願いします。

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

メールアドレスをreno-worksのみにするのは少し弱いね。
これって、使う人が登録する必要性ってあるかな？

アドミンを管理する人だけが、アカウント作成できるようにして、作った人が、使う人にアドレスとパスワードを教える形だったら、RENO社員しか作れないんじゃない?

**Comment by kokihori** [comment]
@shizunaito 
一番上のも弱い気が。パスワードを統一するのは人数が増えた時にややこしくなる。
僕も山田さんと同じく管理者側でアカウントを発行するのが良いと思います。

**Comment by shizunaito** [comment]
@hirokiyamada-reno
@kokihori

アドミンを管理する人が発行するとなると、データベースに直に登録する、というイメージになるのでしょうか。
それで問題なければ確かにそれが1番正確かとは思います。

**Comment by hirokiyamada-reno** [comment]
@shizunaito 

そうだね。データベース直になるかと。
そこまで、数は多くないから、アドミン用の管理ページができるまでは、それでも問題はないと思う。

**Comment by shizunaito** [comment]
@hirokiyamada-reno
承知しました。ではそれで進めます。ありがとうございます。
